@extends('layouts.app')
@section('title', $receipt->code)
@push('styles')<link rel="stylesheet" href="{{ asset('css/ego-gifts.css') }}?v={{ file_exists(public_path('css/ego-gifts.css')) ? filemtime(public_path('css/ego-gifts.css')) : '1.0.0' }}">@endpush
@section('content')
<div class="gift-page">
    <div class="gift-page-head"><div><div class="gift-eyebrow">PHIẾU NHẬP QUÀ TẶNG</div><h1>{{ $receipt->code }}</h1><p>Ngày nhập {{ optional($receipt->receipt_date)->format('d/m/Y') }} · {{ $receipt->supplier_name ?: 'Không ghi nhà cung cấp' }}</p></div>@include('hr.gifts.partials.status',['status'=>$receipt->status])</div>
    @include('hr.gifts.partials.nav')
    @include('hr.gifts.partials.alerts')
    <div class="gift-detail-grid"><section class="gift-card"><div class="gift-card-head"><div><h2>Danh sách quà nhập</h2><p>Tồn kho chỉ được cộng khi phiếu được duyệt.</p></div></div><div class="gift-table-wrap"><table class="gift-table"><thead><tr><th>SKU</th><th>Tên quà</th><th class="text-end">Số lượng</th>@if($canSeeCost)<th class="text-end">Đơn giá</th><th class="text-end">Thành tiền</th>@endif</tr></thead><tbody>@foreach($receipt->items as $item)<tr><td><span class="gift-code">{{ $item->gift->sku ?? '—' }}</span></td><td>{{ $item->gift->name ?? 'Quà đã xóa' }}</td><td class="text-end">{{ number_format((float)$item->quantity,3,',','.') }} {{ $item->gift->unit ?? '' }}</td>@if($canSeeCost)<td class="text-end">{{ number_format((float)$item->unit_cost,0,',','.') }} đ</td><td class="text-end"><strong>{{ number_format((float)$item->line_total,0,',','.') }} đ</strong></td>@endif</tr>@endforeach</tbody></table></div></section><aside class="gift-card"><div class="gift-info-list"><div><span>Người tạo</span><strong>{{ $receipt->creator->name ?? '—' }}</strong></div><div><span>Gửi duyệt lúc</span><strong>{{ optional($receipt->submitted_at)->format('d/m/Y H:i') ?: '—' }}</strong></div><div><span>Người duyệt</span><strong>{{ $receipt->approver->name ?? '—' }}</strong></div><div><span>Ghi sổ tồn kho</span><strong>{{ optional($receipt->posted_at)->format('d/m/Y H:i') ?: 'Chưa ghi' }}</strong></div>@if($receipt->note)<div><span>Ghi chú</span><strong>{{ $receipt->note }}</strong></div>@endif @if($receipt->rejection_reason)<div><span>Lý do từ chối</span><strong class="gift-text-danger">{{ $receipt->rejection_reason }}</strong></div>@endif</div><div class="gift-action-stack">@if($receipt->status==='draft')<form method="post" action="{{ route('hr.gifts.receipts.submit',$receipt) }}">@csrf<button class="gift-btn gift-btn--primary w-100">Gửi duyệt</button></form>@endif @if($canApprove && $receipt->status==='pending')<form method="post" action="{{ route('hr.gifts.receipts.approve',$receipt) }}">@csrf<button class="gift-btn gift-btn--success w-100">Duyệt & cộng tồn</button></form><form method="post" action="{{ route('hr.gifts.receipts.reject',$receipt) }}">@csrf<textarea class="gift-textarea tw:mb-2" name="rejection_reason" placeholder="Lý do từ chối" required></textarea><button class="gift-btn gift-btn--danger w-100">Từ chối</button></form>@endif @if(in_array($receipt->status,['draft','pending','rejected'],true))<form method="post" action="{{ route('hr.gifts.receipts.cancel',$receipt) }}" onsubmit="return confirm('Hủy phiếu nhập này?')">@csrf<button class="gift-btn gift-btn--light w-100">Hủy phiếu</button></form>@endif</div></aside></div>
</div>
@endsection
