@extends('layouts.app')
@section('content')
@php $money=fn($v)=>number_format((float)($v??0),0,',','.').' đ'; $summary=$summary??[]; @endphp
<style>
.fap{padding:18px;background:#f5f7fb;min-height:100%}.fap-hero{padding:28px;border-radius:26px;color:#fff;background:linear-gradient(135deg,#0b1220,#312e81 58%,#6366f1);box-shadow:0 18px 50px rgba(79,70,229,.18)}.fap-card{background:#fff;border:1px solid #e6eaf4;border-radius:18px;padding:20px;box-shadow:0 8px 24px rgba(15,23,42,.05)}.fap-title{font-size:32px;font-weight:950;margin:8px 0}.fap-row{display:grid;grid-template-columns:42px 1fr auto;gap:12px;align-items:center;padding:14px;border:1px solid #edf2f7;border-radius:14px;margin-bottom:10px}.fap-icon{width:38px;height:38px;border-radius:11px;display:grid;place-items:center}.fap-ok{background:#dcfce7;color:#15803d}.fap-warn{background:#fef3c7;color:#b45309}.fap-value{font-weight:900;color:#0f172a}.fap-note{font-size:12px;color:#64748b}.fap-kpi{font-size:25px;font-weight:900}
@media(max-width:768px){.fap{padding:10px}.fap-hero{padding:20px}.fap-title{font-size:25px}.fap-row{grid-template-columns:38px 1fr}.fap-value{grid-column:2}}
</style>
<div class="fap">
<div class="fap-hero tw:mb-6"><div class="tw:flex flex-column flex-lg-row tw:justify-between tw:gap-4"><div><div class="small tw:font-bold tw:uppercase opacity-75">FINANCE AUDIT CENTER</div><h1 class="fap-title">KIỂM TOÁN</h1><div>Rà soát nội bộ số liệu tài chính năm {{ $year }} và các điểm cần đối chiếu trước khi cung cấp hồ sơ kiểm toán.</div></div><form method="GET" class="tw:flex tw:gap-2 tw:items-end"><div><label class="small tw:font-bold">Năm kiểm toán</label><x-ui.input type="number" min="2000" max="2100" name="year" value="{{ $year }}" /></div><x-ui.button variant="warning" type="submit" class="tw:font-bold">Kiểm tra</x-ui.button><x-ui.button variant="light" type="button" onclick="window.print()" class="tw:font-bold">In</x-ui.button></form></div><div class="tw:mt-4 small opacity-75">Kỳ dữ liệu: {{ date('d/m/Y',strtotime($rangeStart)) }} – {{ date('d/m/Y',strtotime($rangeEnd)) }}</div></div>
<div class="tw:row tw:g-3 tw:mb-6"><div class="tw:md:col12-3"><div class="fap-card"><div class="tw:text-[rgba(33,37,41,0.75)] small tw:font-bold">Tổng thu</div><div class="fap-kpi tw:text-[#198754]">{{ $money($summary['total_receipts']??0) }}</div></div></div><div class="tw:md:col12-3"><div class="fap-card"><div class="tw:text-[rgba(33,37,41,0.75)] small tw:font-bold">Tổng chi</div><div class="fap-kpi tw:text-[#dc3545]">{{ $money($summary['total_payments']??0) }}</div></div></div><div class="tw:md:col12-3"><div class="fap-card"><div class="tw:text-[rgba(33,37,41,0.75)] small tw:font-bold">ĐNTT còn chờ</div><div class="fap-kpi">{{ $summary['pending_requests_count']??0 }}</div></div></div><div class="tw:md:col12-3"><div class="fap-card"><div class="tw:text-[rgba(33,37,41,0.75)] small tw:font-bold">Quỹ/tài khoản</div><div class="fap-kpi">{{ $accountsCount }}</div><div class="small tw:text-[rgba(33,37,41,0.75)]">{{ $money($accountsBalance) }}</div></div></div></div>
<div class="tw:row tw:g-4"><div class="tw:min-[75rem]:col12-8"><div class="fap-card"><h4 class="tw:font-bold tw:mb-4">Kết quả rà soát</h4>@foreach($checks as $check)<div class="fap-row"><div class="fap-icon {{ $check['status']==='ok'?'fap-ok':'fap-warn' }}"><i class="bi {{ $check['status']==='ok'?'bi-check-lg':'bi-exclamation-lg' }}"></i></div><div><div class="tw:font-bold">{{ $check['name'] }}</div><div class="fap-note">{{ $check['note'] }}</div></div><div class="fap-value">{{ $check['value'] }}</div></div>@endforeach</div></div>
<div class="tw:min-[75rem]:col12-4"><div class="fap-card tw:mb-6"><h4 class="tw:font-bold">Hồ sơ cần chuẩn bị</h4><div class="fap-note tw:mb-4">Danh sách kiểm tra nội bộ, không thay thế yêu cầu của đơn vị kiểm toán.</div>@foreach(['Báo cáo thu - chi theo kỳ','Danh sách đề nghị thanh toán đã duyệt','Sổ/quỹ ngân hàng và tiền mặt','Danh sách công nợ phải thu','Chứng từ thanh toán liên quan','Hồ sơ công ty và tài liệu đối chiếu'] as $x)<div class="tw:py-2 border-bottom"><i class="bi bi-folder-check tw:mr-2 tw:text-[#0d6efd]"></i>{{ $x }}</div>@endforeach</div><x-ui.button href="{{ route('company-documents.index') }}" variant="primary" class="tw:w-full tw:font-bold"><i class="bi bi-folder2-open me-1"></i>Hồ sơ công ty</x-ui.button></div></div>
</div>
@endsection
