<?php

return [
    'version' => '2.0',

    'status_labels' => [
        'not_assigned' => 'Chưa giao việc',
        'assigned' => 'Đã giao việc',
        'in_progress' => 'Đang thực hiện',
        'submitted' => 'Đã nộp kết quả',
        'approved' => 'Đã duyệt',
        'revision' => 'Cần bổ sung',
    ],

    'status_progress' => [
        'not_assigned' => 0,
        'assigned' => 20,
        'in_progress' => 40,
        'revision' => 40,
        'submitted' => 70,
        'approved' => 100,
    ],

    'role_groups' => [
        'admin' => [
            'admin', 'super_admin', 'management', 'manager', 'director',
            'general_director', 'ban_giam_doc', 'giam_doc', 'quan_tri_he_thong',
        ],
        'technical_manager' => [
            'technical_manager', 'technical_leader', 'truong_phong_ky_thuat',
            'ky_thuat_truong', 'manager_technical',
        ],
        'technical' => [
            'technical', 'technician', 'technical_staff',
            'engineer', 'engineering',
        ],
        'sales' => [
            'sales', 'sale', 'sales_staff', 'sales_manager', 'kinh_doanh',
            'cskh', 'customer_service',
        ],
        'warehouse' => [
            'warehouse', 'kho', 'thu_kho', 'warehouse_manager',
            'inventory', 'inventory_manager',
        ],
        'supervisor' => [
            'supervisor', 'site_supervisor', 'giam_sat', 'can_bo_giam_sat',
            'technical_manager', 'technical_leader', 'truong_phong_ky_thuat',
        ],
    ],

    'steps' => [
        'survey' => [
            'sequence' => 1,
            'label' => 'Khảo sát',
            'short' => 'Khảo sát',
            'icon' => 'bi-camera',
            'tone' => 'sky',
            'weight' => 10,
            'sla_days' => 5,
            'objective' => 'Nắm hiện trạng thực tế công trình làm căn cứ lập phương án.',
            'main_role' => 'Kỹ sư khảo sát',
            'assigner' => 'Trưởng phòng Kỹ thuật',
            'approver' => 'Trưởng phòng Kỹ thuật',
            'assign_groups' => ['technical_manager', 'admin'],
            'assignee_groups' => ['technical', 'supervisor', 'technical_manager'],
            'approval_tracks' => [
                'technical' => ['label' => 'Duyệt kết quả khảo sát', 'groups' => ['technical_manager', 'admin']],
            ],
            'documents' => [
                'survey_report' => ['label' => 'Biên bản khảo sát hiện trạng', 'required' => true, 'min' => 1, 'extensions' => ['pdf']],
                'site_photos' => ['label' => 'Ảnh hiện trạng công trình', 'required' => true, 'min' => 5, 'extensions' => ['jpg', 'jpeg', 'png', 'webp']],
                'measurement_sheet' => ['label' => 'Bảng số liệu đo đạc', 'required' => true, 'min' => 1, 'extensions' => ['xlsx', 'xls', 'csv', 'pdf']],
                'risk_assessment' => ['label' => 'Ý kiến đánh giá rủi ro', 'required' => true, 'min' => 1, 'extensions' => ['pdf', 'doc', 'docx']],
            ],
        ],
        'proposal' => [
            'sequence' => 2,
            'label' => 'Đề xuất phương án',
            'short' => 'Phương án',
            'icon' => 'bi-rulers',
            'tone' => 'violet',
            'weight' => 15,
            'sla_days' => 7,
            'objective' => 'Lập phương án kỹ thuật và báo giá trình khách hàng.',
            'main_role' => 'Kỹ sư thiết kế và Người phụ trách công trình',
            'assigner' => 'Trưởng phòng Kỹ thuật',
            'approver' => 'Trưởng phòng Kỹ thuật duyệt kỹ thuật; Quản trị hệ thống duyệt giá',
            'assign_groups' => ['technical_manager', 'admin'],
            'assignee_groups' => ['technical', 'technical_manager', 'sales'],
            'approval_tracks' => [
                'technical' => ['label' => 'Duyệt phương án kỹ thuật', 'groups' => ['technical_manager', 'admin']],
                'price' => ['label' => 'Duyệt báo giá', 'groups' => ['admin']],
            ],
            'documents' => [
                'technical_proposal' => ['label' => 'Phương án kỹ thuật', 'required' => true, 'min' => 1, 'extensions' => ['pdf']],
                'preliminary_drawing' => ['label' => 'Bản vẽ sơ bộ', 'required' => true, 'min' => 1, 'extensions' => ['pdf', 'dwg', 'dxf']],
                'material_boq' => ['label' => 'Bảng khối lượng vật tư', 'required' => true, 'min' => 1, 'extensions' => ['xlsx', 'xls', 'csv', 'pdf']],
                'approved_quote' => ['label' => 'Báo giá đã duyệt', 'required' => true, 'min' => 1, 'extensions' => ['pdf']],
                'customer_feedback' => ['label' => 'Phản hồi của khách hàng', 'required' => true, 'min' => 1, 'extensions' => ['pdf', 'jpg', 'jpeg', 'png', 'webp', 'eml', 'msg']],
            ],
        ],
        'contract' => [
            'sequence' => 3,
            'label' => 'Ký hợp đồng',
            'short' => 'Hợp đồng',
            'icon' => 'bi-file-earmark-sign',
            'tone' => 'blue',
            'weight' => 10,
            'sla_days' => 5,
            'objective' => 'Chốt điều khoản và ký hợp đồng với khách hàng.',
            'main_role' => 'Người phụ trách công trình',
            'assigner' => 'Quản trị hệ thống',
            'approver' => 'Quản trị hệ thống',
            'assign_groups' => ['admin'],
            'assignee_groups' => ['sales', 'admin', 'technical_manager'],
            'approval_tracks' => [
                'admin' => ['label' => 'Duyệt hợp đồng', 'groups' => ['admin']],
            ],
            'documents' => [
                'signed_contract' => ['label' => 'Hợp đồng đã ký', 'required' => true, 'min' => 1, 'extensions' => ['pdf']],
                'contract_appendix' => ['label' => 'Phụ lục hợp đồng', 'required' => false, 'min' => 1, 'extensions' => ['pdf']],
                'contract_legal_documents' => ['label' => 'Hồ sơ pháp lý', 'required' => false, 'min' => 1, 'extensions' => ['pdf', 'doc', 'docx']],
                'contract_permits' => ['label' => 'Giấy phép / thủ tục liên quan', 'required' => false, 'min' => 1, 'extensions' => ['pdf', 'jpg', 'jpeg', 'png']],
                'contract_other_files' => ['label' => 'File đính kèm khác', 'required' => false, 'min' => 1, 'extensions' => ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'zip']],
            ],
            'data_requirements' => [
                'technical_feasibility_confirmed' => 'Xác nhận tiến độ khả thi của Trưởng phòng Kỹ thuật',
                'contract_signed_at' => 'Ngày ký hợp đồng',
                'contract_amount_after_vat' => 'Tổng giá trị hợp đồng sau VAT',
                'target_completion_at' => 'Ngày cam kết hoàn thành',
            ],
        ],
        'legal' => [
            'sequence' => 4,
            'label' => 'Hồ sơ pháp lý',
            'short' => 'Pháp lý',
            'icon' => 'bi-file-earmark-lock',
            'tone' => 'amber',
            'weight' => 10,
            'sla_days' => 7,
            'objective' => 'Hoàn tất thủ tục pháp lý để được phép thi công.',
            'main_role' => 'Người phụ trách công trình',
            'assigner' => 'Quản trị hệ thống',
            'approver' => 'Quản trị hệ thống',
            'assign_groups' => ['admin'],
            'assignee_groups' => ['sales', 'admin', 'technical_manager'],
            'approval_tracks' => [
                'admin' => ['label' => 'Duyệt hồ sơ pháp lý', 'groups' => ['admin']],
            ],
            'documents' => [
                'construction_permit' => ['label' => 'Giấy phép thi công', 'required' => true, 'min' => 1, 'extensions' => ['pdf']],
                'site_access_registration' => ['label' => 'Đăng ký ra vào công trình', 'required' => true, 'min' => 1, 'extensions' => ['pdf', 'jpg', 'jpeg', 'png', 'webp']],
                'safety_plan' => ['label' => 'Phương án an toàn lao động', 'required' => true, 'min' => 1, 'extensions' => ['pdf']],
                'grid_connection_file' => ['label' => 'Hồ sơ đấu nối điện lực', 'required' => false, 'conditional_key' => 'requires_grid_connection', 'min' => 1, 'extensions' => ['pdf']],
                'project_insurance' => ['label' => 'Bảo hiểm công trình', 'required' => false, 'conditional_key' => 'requires_insurance', 'min' => 1, 'extensions' => ['pdf']],
            ],
        ],
        'construction' => [
            'sequence' => 5,
            'label' => 'Thi công',
            'short' => 'Thi công',
            'icon' => 'bi-tools',
            'tone' => 'teal',
            'weight' => 35,
            'sla_days' => null,
            'objective' => 'Hoàn thành khối lượng đúng bản vẽ, đúng tiến độ và bảo đảm an toàn.',
            'main_role' => 'Đội thi công và Cán bộ giám sát',
            'assigner' => 'Trưởng phòng Kỹ thuật',
            'approver' => 'Trưởng phòng Kỹ thuật',
            'assign_groups' => ['technical_manager', 'admin'],
            'assignee_groups' => ['technical', 'supervisor', 'technical_manager'],
            'approval_tracks' => [
                'technical' => ['label' => 'Duyệt kết quả thi công', 'groups' => ['technical_manager', 'admin']],
            ],
            'documents' => [
                'construction_plan' => ['label' => 'Kế hoạch thi công', 'required' => true, 'min' => 1, 'extensions' => ['xlsx', 'xls', 'csv', 'pdf']],
                'daily_construction_log' => ['label' => 'Nhật ký thi công', 'required' => true, 'min' => 1, 'extensions' => ['pdf', 'jpg', 'jpeg', 'png', 'webp']],
                'site_progress_media' => ['label' => 'Ảnh và video hiện trường', 'required' => true, 'min' => 2, 'extensions' => ['jpg', 'jpeg', 'png', 'webp', 'mp4', 'mov']],
                'incident_report' => ['label' => 'Biên bản sự cố và giải trình', 'required' => false, 'conditional_key' => 'has_incident', 'min' => 1, 'extensions' => ['pdf']],
                'internal_acceptance_report' => ['label' => 'Báo cáo nghiệm thu nội bộ', 'required' => true, 'min' => 1, 'extensions' => ['pdf']],
                'approved_material' => ['label' => 'Phiếu vật tư đã được Quản trị hệ thống duyệt', 'required' => true, 'min' => 1, 'extensions' => ['pdf', 'xlsx', 'xls', 'csv', 'jpg', 'jpeg', 'png', 'webp']],
            ],
        ],
        'acceptance' => [
            'sequence' => 6,
            'label' => 'Nghiệm thu và bàn giao',
            'short' => 'Nghiệm thu',
            'icon' => 'bi-clipboard2-check',
            'tone' => 'indigo',
            'weight' => 15,
            'sla_days' => 10,
            'objective' => 'Hoàn tất xác nhận của khách hàng và hồ sơ hoàn công.',
            'main_role' => 'Người phụ trách công trình',
            'assigner' => 'Trưởng phòng Kỹ thuật',
            'approver' => 'Quản trị hệ thống',
            'assign_groups' => ['technical_manager', 'admin'],
            'assignee_groups' => ['sales', 'technical', 'supervisor', 'warehouse'],
            'approval_tracks' => [
                'admin' => ['label' => 'Duyệt nghiệm thu và bàn giao', 'groups' => ['admin']],
            ],
            'documents' => [
                'customer_acceptance' => ['label' => 'Biên bản nghiệm thu có chữ ký khách hàng', 'required' => true, 'min' => 1, 'extensions' => ['pdf']],
                'as_built_drawing' => ['label' => 'Bản vẽ hoàn công', 'required' => true, 'min' => 1, 'extensions' => ['pdf', 'dwg', 'dxf']],
                'test_certificates' => ['label' => 'Kết quả đo kiểm và chứng chỉ thiết bị', 'required' => true, 'min' => 1, 'extensions' => ['pdf']],
                'handover_minutes' => ['label' => 'Biên bản bàn giao', 'required' => true, 'min' => 1, 'extensions' => ['pdf']],
                'material_reconciliation' => ['label' => 'Bảng quyết toán vật tư', 'required' => true, 'min' => 1, 'extensions' => ['xlsx', 'xls', 'csv', 'pdf']],
                'completion_photos' => ['label' => 'Ảnh công trình hoàn thiện', 'required' => true, 'min' => 10, 'extensions' => ['jpg', 'jpeg', 'png', 'webp']],
            ],
        ],
        'warranty' => [
            'sequence' => 7,
            'label' => 'Bảo hành',
            'short' => 'Bảo hành',
            'icon' => 'bi-shield-check',
            'tone' => 'green',
            'weight' => 5,
            'sla_days' => null,
            'objective' => 'Duy trì cam kết bảo hành và theo dõi công trình sau bàn giao.',
            'main_role' => 'Người phụ trách công trình',
            'assigner' => 'Trưởng phòng Kỹ thuật',
            'approver' => 'Trưởng phòng Kỹ thuật',
            'assign_groups' => ['technical_manager', 'admin'],
            'assignee_groups' => ['sales', 'technical', 'supervisor', 'technical_manager'],
            'approval_tracks' => [
                'technical' => ['label' => 'Duyệt kết quả bảo hành', 'groups' => ['technical_manager', 'admin']],
            ],
            'documents' => [
                'warranty_request' => ['label' => 'Phiếu yêu cầu bảo hành', 'required' => true, 'min' => 1, 'extensions' => ['pdf', 'jpg', 'jpeg', 'png', 'webp']],
                'warranty_resolution' => ['label' => 'Biên bản xử lý bảo hành có xác nhận khách hàng', 'required' => true, 'min' => 1, 'extensions' => ['pdf']],
                'before_after_photos' => ['label' => 'Ảnh trước và sau khi xử lý', 'required' => true, 'min' => 2, 'extensions' => ['jpg', 'jpeg', 'png', 'webp']],
                'replacement_material' => ['label' => 'Phiếu vật tư thay thế', 'required' => false, 'conditional_key' => 'uses_replacement_material', 'min' => 1, 'extensions' => ['pdf', 'xlsx', 'xls']],
            ],
            'system_requirements' => [
                'maintenance_schedule' => 'Đã thiết lập lịch bảo trì định kỳ trên hệ thống',
            ],
        ],
    ],

    'legacy_phase_map' => [
        'init' => 'survey',
        'design' => 'proposal',
        'prepare' => 'legal',
        'execute' => 'construction',
        'om' => 'warranty',
    ],

    'step_to_legacy_phase' => [
        'survey' => 'design',
        'proposal' => 'design',
        'contract' => 'prepare',
        'legal' => 'prepare',
        'construction' => 'execute',
        'acceptance' => 'execute',
        'warranty' => 'om',
    ],
];
