@extends('layouts.app')
@section('title', $giftRequest->code)
@push('styles')<link rel="stylesheet" href="{{ asset('css/ego-gifts.css') }}?v={{ file_exists(public_path('css/ego-gifts.css')) ? filemtime(public_path('css/ego-gifts.css')) : '1.0.0' }}">@endpush
@section('content')
<div class="gift-page">
    <div class="gift-page-head"><div><div class="gift-eyebrow">YÊU CẦU TẶNG QUÀ</div><h1>{{ $giftRequest->code }}</h1><p>{{ $giftRequest->customer_name }} · {{ $giftRequest->customer_phone ?: 'Chưa có SĐT' }}</p></div>@include('hr.gifts.partials.status',['status'=>$giftRequest->status])</div>
    @include('hr.gifts.partials.nav')
    @include('hr.gifts.partials.alerts')
    <div class="gift-detail-grid">
        <section class="gift-card"><div class="gift-card-head"><div><h2>Danh sách quà</h2><p>Khi duyệt, hệ thống trừ tồn đúng số lượng bên dưới.</p></div></div><div class="gift-table-wrap"><table class="gift-table"><thead><tr><th>SKU</th><th>Tên quà</th><th>ĐVT</th><th class="text-end">Số lượng</th>@if($canSeeCost)<th class="text-end">Giá vốn tham chiếu</th>@endif</tr></thead><tbody>@foreach($giftRequest->items as $item)<tr><td><span class="gift-code">{{ $item->gift->sku ?? '—' }}</span></td><td><strong>{{ $item->gift->name ?? 'Quà đã xóa' }}</strong>@if($item->note)<small>{{ $item->note }}</small>@endif</td><td>{{ $item->gift->unit ?? '—' }}</td><td class="text-end"><strong>{{ number_format((float)$item->quantity,3,',','.') }}</strong></td>@if($canSeeCost)<td class="text-end">{{ number_format((float)$item->unit_cost_snapshot,0,',','.') }} đ</td>@endif</tr>@endforeach</tbody></table></div></section>
        <aside class="gift-card"><div class="gift-info-list"><div><span>Khách hàng</span><strong>{{ $giftRequest->customer_name }}</strong></div><div><span>Địa chỉ giao</span><strong>{{ $giftRequest->delivery_address ?: '—' }}</strong></div><div><span>Ngày dự kiến</span><strong>{{ optional($giftRequest->expected_delivery_date)->format('d/m/Y') ?: '—' }}</strong></div><div><span>Lý do tặng</span><strong>{{ $giftRequest->reason ?: '—' }}</strong></div><div><span>Người tạo</span><strong>{{ $giftRequest->creator->name ?? '—' }}</strong></div><div><span>Người duyệt</span><strong>{{ $giftRequest->approver->name ?? '—' }}</strong></div><div><span>Thời điểm trừ tồn</span><strong>{{ optional($giftRequest->stock_deducted_at)->format('d/m/Y H:i') ?: 'Chưa trừ' }}</strong></div>@if($giftRequest->delivery_note)<div><span>Ghi chú giao quà</span><strong>{{ $giftRequest->delivery_note }}</strong></div>@endif @if($giftRequest->rejection_reason)<div><span>Lý do từ chối</span><strong class="gift-text-danger">{{ $giftRequest->rejection_reason }}</strong></div>@endif</div>
            <div class="gift-action-stack">
                @if($giftRequest->status==='draft')<form method="post" action="{{ route('hr.gifts.requests.submit',$giftRequest) }}">@csrf<button class="gift-btn gift-btn--primary w-100">Gửi duyệt</button></form>@endif
                @if($canApprove && $giftRequest->status==='pending')<form method="post" action="{{ route('hr.gifts.requests.approve',$giftRequest) }}">@csrf<button class="gift-btn gift-btn--success w-100">Duyệt & trừ tồn</button></form><form method="post" action="{{ route('hr.gifts.requests.reject',$giftRequest) }}">@csrf<textarea class="gift-textarea tw:mb-2" name="rejection_reason" required placeholder="Lý do từ chối"></textarea><button class="gift-btn gift-btn--danger w-100">Từ chối</button></form>@endif
                @if($canHandleStock && in_array($giftRequest->status,['approved','preparing','delivering','failed','delivered'],true))<form method="post" action="{{ route('hr.gifts.requests.status',$giftRequest) }}">@csrf<label>Cập nhật giao quà<select class="gift-select tw:mb-2" name="status" required>@foreach(['preparing'=>'Đang chuẩn bị','delivering'=>'Đang giao','delivered'=>'Đã giao','failed'=>'Giao thất bại','returned'=>'Hoàn về kho'] as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></label><textarea class="gift-textarea tw:mb-2" name="delivery_note" placeholder="Ghi chú giao nhận"></textarea><button class="gift-btn gift-btn--secondary w-100">Cập nhật trạng thái</button></form>@endif
                @if(in_array($giftRequest->status,['draft','pending','rejected'],true))<form method="post" action="{{ route('hr.gifts.requests.cancel',$giftRequest) }}" onsubmit="return confirm('Hủy yêu cầu này?')">@csrf<button class="gift-btn gift-btn--light w-100">Hủy yêu cầu</button></form>@endif
            </div>
        </aside>
    </div>
</div>
@endsection
